version: "3"
services:
  app:
    # Use either build or image, but not both. Uncomment the needed line.
    image: localhost/phlox-dev:latest
    #build: .
    container_name: phlox-dev
    network_mode: host
    environment:
      DB_ENCRYPTION_KEY: ${DB_ENCRYPTION_KEY}
      NODE_ENV: development
      VITE_BACKEND_URL: ""
      TZ: Australia/Melbourne
      LLM_EXTRA_BODY: '{"extra_body": {"chat_template_kwargs": {"enable_thinking": true}}}'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - ./data:/usr/src/app/data # Only for persistent data
      - ./logs:/usr/src/app/logs # Optional: Persist logs
